# Site settings
title: 郝锡强的博客
email: haoxiqiang@live.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opentalking.org" # the base hostname & protocol for your site
twitter_username: haoxiqiang
github_username:  haoxiqiang

# Build settings
markdown: kramdown
encoding: utf-8
