title: 郝锡强的博客
tagline:
author:
  name:              "haoxiqiang"
  email:             "haoxiqiang@live.com"
  github:            "haoxiqiang"
  qq:                "653979558"

#production_url是sitemap.txt生成的url,方便百度谷歌收录
production_url: http://haoxiqiang.github.io
#
# Jekyll Settings
#

# Serving
url: "http://haoxiqiang.github.io"
baseurl: ""

# Handling Reading
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
textile_ext:  "textile"

#markdown: rdiscount
markdown: kramdown
highlighter:         rouge
permalink:           none
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: /blog/page/:num
permalink: /:categories/:year:month:day-:title.html
gems: [jekyll-paginate]

sass:
  sass_dir: _sass
  style: compressed
  compile_in_place: true


# Site Settings
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact






